name: CI

on:
  issues:
    types:
      - opened

jobs:
  add-issue-comment:
    uses: rednafi/i-have-seen/.github/workflows/seen.yml@main
    with:
      message: |
        Simple comment **works**.
        This is another ~line~.

      where: "issues"
