name: CI

on:
  issues:
  # issue comment
  issue_comment:


jobs:
  call-workflow-passing-data:
    uses: rednafi/i-have-seen/.github/workflows/seen.yml@dev
    with:
      message: This is a custom message
      where: "issues"
