name: Attach "I have seen" messages to issues or pull requests.

on:
  workflow_call:
    inputs:
      message:
        description: "Message that should be attached to the issue or pull request."
        default: "I have seen"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        run:
          echo ${{ inputs.message }} @$(date -u --rfc-3339=s).
