name: Attach "I have seen" messages to issues or pull requests.

on:
  workflow_call:
    inputs:
      message:
        description: "Message body that should be attached to an issue or a pull request."
        default: "I have seen @$(date -u --rfc-3339=s)"
        required: false
        type: string

      where:
        description: "Where to post the message. e.g on an issue or a pull request."
        default: "issues"
        required: false
        type: string

jobs:
  send-message:
    runs-on: ubuntu-latest
    env:
      MESSAGE: ${{ inputs.message }}
      GITHUB_REPOSITORY: ${{ github.repository }}  # e.g. ococat/hello-world
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH # e.g. event or pull request number.
    steps:
      - name: Add message as an issue comment.
        if: ${{ inputs.where == 'issues' && github.event_name == 'issues'}}
        run: |
          issue_number=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")

          echo -E "$MESSAGE"

          curl --request POST \
          --url "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$issue_number/comments" \
          --header "authorization: Bearer $GITHUB_TOKEN" \
          --header "content-type: application/json" \
          -d '{ "body":' "$MESSAGE" '}' \
          --fail

      # - name: Add message as a pull request comment.
      #   if: ${{ inputs.where == 'pull_request' && github.event_name == 'pull_request' }}
      #   run:
      #     echo $MESSAGE in pull request
