name: Test

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-issue-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Issue comment
        uses: rednafi/i-have-seen@main
        with:
          message: |
            Simple comment **works**.
            This is another ~line~.

          where: "issues"

  add-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: PR comment
        uses: rednafi/i-have-seen@main
        with:
          message: |
            Simple comment **works**.
            This is another ~line~.

          where: "pull_request"
