name: CI

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-issue-comment:
    id: issue-comment
    uses: ./
    with:
      message: |
        Simple comment **works**.
         This is another ~line~.

      where: "issues"

  add-pr-comment:
    id: pr-comment
    uses: ./
    with:
      message: |
        Simple comment **works**.
         This is another ~line~.

      where: "pull_request"
